# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 20:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.wagtailcore.models
import wagtail.wagtailsearch.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0032_add_bulk_delete_page_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='documents', verbose_name='file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('distance', models.IntegerField(default=0, verbose_name='distancia')),
                ('elevation', models.IntegerField(default=0, verbose_name='desnivel')),
                ('moving_time', models.IntegerField(default=0, verbose_name='tiempo en movimiento')),
                ('elapsed_time', models.IntegerField(default=0, verbose_name='tiempo total')),
                ('max_elevation', models.IntegerField(default=0, verbose_name='altura máxima')),
                ('max_velocity', models.FloatField(default=0, verbose_name='velocidad máxima')),
                ('start_lat', models.FloatField(default=0, verbose_name='latitud')),
                ('start_lon', models.FloatField(default=0, verbose_name='longitud')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='fecha realización')),
                ('collection', models.ForeignKey(default=wagtail.wagtailcore.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'document',
            },
            bases=(wagtail.wagtailsearch.index.Indexed, models.Model),
        ),
    ]
