# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='elevation',
            new_name='uphill',
        ),
        migrations.AddField(
            model_name='track',
            name='downhill',
            field=models.IntegerField(default=0, verbose_name='desnivel'),
        ),
    ]
