# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 18:30
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20170317_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='downloads',
            field=models.IntegerField(default=0, verbose_name='Descargas'),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/track_files/', location='/home/carsol/projects/montrack/montrack/track_files'), upload_to='', verbose_name='Track'),
        ),
    ]
